-- MySQL Script generated by MySQL Workbench
-- Mon Apr 24 21:04:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `devis`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devis` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `delivery` TINYINT NULL,
  `comment` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `event`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `event` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `testimonial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `testimonial` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `testimonial` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `recipe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `recipe` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `content` TEXT NULL,
  `back_content` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `category` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` LONGTEXT NULL,
  `information` LONGTEXT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_product_category1_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devis_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `devis_product` (
  `devis_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`devis_id`, `product_id`),
  INDEX `fk_devis_has_product_product1_idx` (`product_id` ASC) VISIBLE,
  INDEX `fk_devis_has_product_devis1_idx` (`devis_id` ASC) VISIBLE,
  CONSTRAINT `fk_devis_has_product_devis1`
    FOREIGN KEY (`devis_id`)
    REFERENCES `devis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_devis_has_product_product1`
    FOREIGN KEY (`product_id`)
    REFERENCES `product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE tafforet;

	INSERT INTO `event` (`text`)
VALUES (
        'Marché de Rochefort tous les mardis.'
    ), (
        'Marché de Saujon tous les jeudis.'
    ), (
        'Dégustation et visite de l’entreprise le samedi matin sur réservation.'
    );

	INSERT INTO `category` (type) VALUES ('huître'), ('moule');

    INSERT INTO `testimonial` (`testimonial`)
VALUES (
        '“Miam miam trop bonnes les huîtres”'
    ), (
        '“Huîtres fraîches et de qualités ! JFM.”'
    ), (
        '“J\'ai rarement goûté des huîtres aussi fraîches et savoureuses que celles-ci”'
    );

	INSERT INTO `category` (type) VALUES ('huître'), ('moule');


INSERT INTO `product` (
		`name`,
	 	`description`,
	  	`information`,
	   	`category_id`
		)
VALUES (
	'Fine de Claires',
	'Les huîtres de type fines de claire sont cultivées dans des bassins
    d’eau salée appelés claires. Elles peuvent être de couleur
    blanche ou verte et sont affinées hors de la mer pendant un à deux mois,
    avec un maximum de 20 coquillages par mètre carré. La chair de la fine de claire
    est plus ferme que celle
    des huîtres de parc et a un léger goût de noisette. Bien que leur teneur en chair
    soit la même que celle des huîtres de parc, les fines de claire ont une forme arrondie et bombée.',
    'Du 1/04 au 31/10 : 14 jours <br> Du 1/11 au 31/03 : 28 jours',
    1
), (
	'Spéciale de Claires',
	'La spéciale de claire est une variété d’huîtres élevée dans des bassins d’eau salée appelés
	claires. Ce type d’huître a été engraissé pendant une période plus longue allant de deux
	à quatre mois, avec une densité d’élevage très réduite de seulement deux à six
	individus par mètre carré. Les spéciales de claire sont connues pour être particulièrement
	dodues et délicieuses.
	La faible densité d’élevage est intentionnelle pour obtenir une huître plus
	charnue avec une saveur plus prononcée. Les spéciales de claire ont une coquille
	creuse et arrondie et sont moins salées que les fines de claire.',
	'Du 1/04 au 31/10 : 14 jours<br> Du 1/11 au 31/03 : 28 jours',
    1
), (
	'Pousse en Claires',
	'La variété d’huîtres nommée fine de claire verte Label Rouge
	est connue pour sa texture peu charnue et sa forme homogène. Les branchies
	de ces huîtres sont d’une teinte verte appréciée des consommateurs, et leur
	manteau est translucide voir blanc, sans présence de laitance. Leur saveur est équilibrée,
	avec un goût salé suivi d’une note sucrée et un arôme de terroir de claires.
	La consistance de ces huîtres peut aller de molle à un peu ferme, et leur longueur en
	bouche est moyenne.',
	'4 mois minimum',
	1
), (
    'Label Rouge (verdissement)',
    'Les ostréiculteurs sont fiers de produire cette huître exceptionnelle.
    Elle est élevée à très
    faible densité, avec un maximum de 5 individus par mètre carré dans une claire, et ce
    pendant une période de 4 à 8 mois,
    en fonction de la saison. Au cours de sa croissance, l’huître forme des
    lignes de pousses en dentelle sur sa coquille. Dans les claires,
    elle développe une chair ferme et croquante avec un taux de chair élevé.
    Lors de la dégustation, cette huître offre une saveur douce et charnue avec une note de noisette,
    et sa longueur en bouche est soutenue.',
    'Du 1/04 au 31/10 : 14 jours <br> Du 1/11 au 31/03 : 28 jours',
    1
), (
    'Moule de bouchot',
    'La moule de bouchot est une variété de moule cultivée sur
    des pieux en bois, appelés bouchots, qui sont plantés dans la mer.
    Cette technique d’élevage permet de produire des moules de haute qualité,
    car elles sont nourries par les nutriments présents dans l’eau de mer
    et protégées des prédateurs terrestres. Les bouchots sont placés dans des
    zones de faible profondeur, où les moules peuvent se développer dans un environnement protégé.
    Elles sont appréciées pour leur chair ferme et savoureuse, ainsi que pour
    leur faible teneur en sable et en algues.',
    NULL,
    2
), (
    'Moule d’Irlande',
    'La moule d’Irlande est une variété de moule cultivée dans
    les eaux froides et cristallines
    de l’Atlantique Nord. Elle est appréciée pour sa chair ferme et son goût
    délicat, qui rappelle celui des fruits de mer frais.
    La moule d’Irlande est élevée sur des cordes qui sont suspendues à des
    bouées en mer, où elles se nourrissent de phytoplancton et
    de nutriments marins. Ce mode d’élevage permet de produire des moules
    de grande qualité, car elles sont constamment baignées dans l’eau de mer
    pure et riche en nutriments.',
    NULL,
    2
);
